apiVersion: v1
kind: Pod
metadata:
  name: netology-web
  labels:
    app: second-app

spec:
  containers:
    - image: gcr.io/kubernetes-e2e-test-images/echoserver:2.2
      name: test2-image
      ports:
        - containerPort: 8080